[package]
name = "macroquad-egui"
version = "0.1.0"
edition = "2021"
# macroquad 0.3.26 requires MSRV 1.73
rust-version = "1.73"

[dependencies]
egui = "0.21.0"
egui-macroquad = "0.15"
macroquad = { version = "0.4.5", default-features = false }
